config/routes.rb
Rails.application.routes.draw do
  resources :properties
  root :to => redirect('/home')
  
  get '/home' => 'sessions#home'
  post '/search' => 'sessions#search'
  get '/join/:id/:pid' => 'sessions#sendreq'
  get '/create' => 'sessions#create'
  get '/signin' => 'sessions#signin'
  post '/signin/:op' => 'sessions#new'
  post '/create/manager/:op' => 'sessions#createManager'
  post '/create/tenant/:op' => 'sessions#createTenant'
  get  'auth/:provider/callback' => 'sessions#facebookcheck'
  get '/create/manager' => 'sessions#createManager'
  get '/create/tenant' => 'sessions#createTenant'
  get 'logout' => 'sessions#destroy'
  get  'auth/failure' => 'sessions#failure'
  get  'auth/facebook', :as => 'login'
  get '/create/manager/check' => 'sessions#Managerfb'
  get '/create/tenant/check' => 'sessions#Tenantfb'
  get '/create/check' => 'sessions#signinfb'
  
  get '/request/:op/:id' => 'managers#respond'
  get '/managers/show' => 'managers#show'
  get '/managers/edit' => 'managers#edit'
  patch '/managers/edit' => 'managers#update'
  
  get '/tenants/show' => 'tenants#show'
  get '/tenants' => 'tenants#index'
  get '/tenants/new' => 'tenants#new'
  post '/tenants/new' => 'tenants#create'
  get '/tenants/edit' => 'tenants#edit'
  patch '/tenants/edit' => 'tenants#update'
  get '/tenants/pay' => 'tenants#pay'
  get '/tenants/pay/:id' => 'tenants#stripepay'
  get '/tenants/:op/:id' => 'tenants#service'

  get '/properties' => 'properties#index'
  get '/properties/:id' => 'properties#show'
  get '/properties/new' => 'properties#new'
  post '/properties/new' => 'properties#create'
  get '/properties/:id/edit' => 'properties#edit'
  delete '/properties/:id/delete' => 'properties#destroy'
  
  get '/services/new' => 'services#new'
  post '/services/new' => 'services#create'
  get '/services' => 'services#index'
  get '/services/:id' => 'services#show'
  
    get 'auth/guest', to: 'sessions#create_guest'
    get 'auth/loggedin', to: 'sessions#loggedin'
  

end

app/models/tenant.rb
class Tenant < ActiveRecord::Base
    #tenant can only belong to one property 
    belongs_to :property
    has_many :joinrequests, dependent: :destroy
    has_many :services, dependent: :destroy
    has_and_belongs_to_many :rent
    validates :name, :presence => true
    validates :email, :presence => true, :uniqueness => true
    def self.create_with_omniauth(auth)
    Tenant.create!(
      :provider => auth["provider"],
      :uid => auth["uid"],
      :name => auth["info"]["name"],
      :email => auth["info"]["email"],
      :phone_number => auth["info"]["phone"])
  end
end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
 skip_before_action :verify_authenticity_token
 #before_action :force_log_in
 before_action :confirm_logged_in
 require 'stripe'
 Stripe.api_key = "sk_live_8NHE2vkkiUHunwbpPYZFrG0L"
 
 #gets all tenants that have the same property id# 
  def index
    @tenants = Tenant.where(:property_id => @property)
  end
  
 #shows tenant with user id that matches the tenant logged in#
  def show
    @tenant = Tenant.find(session[:user_id]) 
   #makes sure tenant has a property id to search for its roommates, property, and services# 
    unless @tenant.property_id.blank?
      @property = Property.find(@tenant.property_id)
      @roommates = Tenant.where("property_id = ? AND id != ?", @property.id, @tenant.id)
      @services = Service.where("tenant_id = ? AND resolved = ?", @tenant.id, true)
      @roommateRentTot = 0
      #checks if roommates are empty before calculating total rent 
      unless @roommates.empty?
        @roommates.each do |r| 
          if not r.rentNum.nil?
            @roommateRentTot += r.rentNum ||= 0
          end
        end
      end
      if not @tenant.rentNum.nil?
        @roommateRentTot +=  @tenant.rentNum
      end
      if params[:code]
          uri = URI.parse("https://connect.stripe.com/oauth/token")
          @response = Net::HTTP.post_form(uri, "client_secret" => "sk_live_8NHE2vkkiUHunwbpPYZFrG0L",
            "code" => params[:code],
            "grant_type" => "authorization_code")
          @JSONResponse = JSON.parse(@response.body)
          puts @response.body
          @tenant.stripe_user_id = @JSONResponse["stripe_user_id"]
          if @tenant.save
            render 'show'
          else
            flash[:notice] = "You were unable to add a Stripe account. Please try again."
            render 'show'
          end
      end
    end
  end
  
  #An incomplete function that would allow tenants to pay landlords directly through the Stripe payment service. #
  def stripepay
    @rent = Rent.find(params[:id])
    @tenant = Tenant.find(session[:user_id])
    @property = Property.find(@tenant.property_id)
    @manager = Manager.find(@property.manager_id)
    @Customer = Stripe::Customer.retrieve(@tenant.stripe_user_id)
    @charge = Stripe::Charge.create({
      :amount => @tenant.rentNum,
      :currency => 'usd',
      :customer => @Customer,
      :destination => {
        :acount => @manager.stripe_user_id } ,
      :description => "#{@property.name} Rent #{@rent.due}, #{@tenant.name}"})
  end
  
  def service
    @service = Service.find(params[:id])
    if params[:op] == 'completed'
      @service.delete
    else
      @service.resolved = false
      @service.save
    end
    redirect_to '/tenants/show'
  end
  
 #creates the tenant with the inputs created by the tenant log in#
  def create
     params_map = ActiveSupport::HashWithIndifferentAccess.new(params[:tenant])
    @tenant = Tenant.new(params_map)
    if @tenant.save
      redirect_to @tenant
    else
      render "new"
    end
  end
  
  #allows tenants to edit information# 
  def edit
    @tenant = Tenant.find(session[:user_id])
  end
  
  #maps the edits from edit to the tenants profile 
  def update
      @tenant = Tenant.find(session[:user_id])
      params_map = ActiveSupport::HashWithIndifferentAccess.new(params[:tenant])
      @tenant.update(params_map)
      redirect_to '/tenants/show'
  end
  

  def dummypay
    @rent = Rent.find(params[:id])
    @tenant = Tenant.find(session[:user_id])
    @rent.total -= @tenant.rentNum
    @rent.save
    redirect_to '/tenants/show'
  end
end

app/helpers/tenant_helper.rb
module TenantHelper
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/views/tenants/edit.html.erb
<!DOCTYPE html>
<html>
    <head>
        <% @title="Tenant Edit Page: Abode" %>
    </head>
    <%= render '/layouts/manager_nav_bar' %>
    <% if flash[:notice] %>
        <div class="card-panel teal lighten-2 col s3 white-text">
            <%= flash[:notice] %>
        </div>
    <% end %>
    <body>
        <div class = "container">
            <div class = "row">
                <h3>
                   Edit Tenant Information
                </h3>
            </div>
            <div class = "row">
                <%= form_for @tenant, url: {action: "edit"} do |f| %>
                    <div class = "row">
                        <div class = "col s3">
                            <label for="tenant_name">Name</label>
                            <%=  f.text_field :name, :class => "input-field "%>
                        </div>
                        <div class = "col s3">
                            <label for="tenant_email">Email</label>
                            <%=  f.text_field :email, :class => "input-field" %>
                        </div>
                        <div class = "col s3"
                            <label for="tenant_phone_number">Phone Number</label>
                            <%=  f.number_field :phone_number, :class => "input-field" %>
                        </div>
                        <div class = "col s3"
                            <label for="tenant_rentNum">Monthly Rent</label>
                            <%=  f.text_field :rentNum, :class => "input-field" %>
                        </div>
                    </div>
                    <div class = "row">
                        <div class = "col s3">
                            <%= f.submit "Update", class: "btn btn-primary" %>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    </body>
</html>

app/views/tenants/index.html.erb
<<!DOCTYPE html>

<html>
    <% if flash[:notice] %>
        <div class="card-panel teal lighten-2 col s3 white-text">
            <%= flash[:notice] %>
        </div>
    <% end %>
    <head>
        <% @title="Tenant Info Page: Abode" %>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    </head>
    <body>
        <div class = "container">
            <div class = "row">
                <h1>My Profile</h1>
            </div>
            <div class = "row">
                <table class = "highlight">
                    <thead>
                        <th></th>
                        <th>Name</th>
                        <th>Phone Number</th>
                        <th>Email</th>
                        <th>Provider</th>
                        <th>Uid</th>
                    </thead>
                    <tbody>
                        <%if @tenants
                        @tenants.each do |t| %>
                            <tr>
                                <td>  <a class "waves-effect waves-teal btn-flat" href="<%= tenants_path %>/<%= t.id %>"><%= t.name %> </a> </td>
                                <td><%= t.email %></td>
                                <td><%= t.phone_number%> </td>
                                <td><%= t.uid%>   </td>
                                <td><%= t.provider%>   </td>
                                <td>  <a class "waves-effect waves-teal btn-flat" href="<%= tenants_path %>/<%= t.id %>/edit" id = "Edit">Edit</a> </td>
                            </tr>
                        <%end 
                         end%>
                     </tbody>
                </table>
            </div>
            <div class = "row">
                <br/>
                <div>
                    <a class = "waves-effect waves-light btn" href = "<%=tenants_path%>/new" id = "create">Create New</a>
                </div>
            </div>
        </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    </body>
</html>

app/views/tenants/new.html.erb
<!DOCTYPE html>
<html>
    <head>
        <% @title="Create New Tenant Page: Abode" %>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    </head>
    <body>
        <nav>
            <div class="nav-wrapper orange darken-4">
                <a href="<%=tenants_path %>" class="brand-logo">Home</a>
                <ul id="nav-mobile" class="right hide-on-med-and-down">
                    <li><a href="#">Buttons!</a></li>
                    <li><a href="#">Buttons!</a></li>
                    <li><a href="#">Buttons!</a></li>
                </ul>
            </div>
        </nav>
        <div class = "container">
            <div class = "row">
                <h3>
                    Create New Tenant
                </h3>
            </div>
            <div class = "row">
                <form class = "col s12" action = "<%tenants_path%>" method = "post">
                    <div class = "row">
                        <div class = "input-field col s12">
                            <input id="tenant_name" name = "tenant[name]" size="22" type="text" class="validate">
                            <label for="tenant_name">Tenant Name</label>
                        </div>
                    <div class = "row">
                        <div class = "input-field col s6">
                            <input id="phone_number" name = "tenant[phone_number]" type="text" class="validate">
                            <label for="phone_number">Phone Number</label>
                        </div>
                        <div class = "input-field col s6">
                            <input id="email" name = "tenant[email]" size="25 "type="text" class="validate">
                            <label for="email">Email</label>
                        </div>
                    <div class = "input-field col s3">
                        <input name="commit" type="submit" value="Create"/>
                        
                    </div>
                </form>
            </div>
        </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    </body>
</html>

app/views/tenants/show.html.erb
<!DOCTYPE html>
<html>
    <% @title="Tenant Profile Page: Abode" %>
     <%= render '/layouts/tenant_nav_bar' %>
     <% if flash[:notice] %>
        <div class="card-panel teal lighten-2 col s3 white-text">
            <%= flash[:notice] %>
        </div>
    <% end %>
    <head>
      <meta http-equiv="X-UA-Compatible" content="IE=edge" />
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <script src="https://www.paypalobjects.com/api/checkout.js"></script>
    </head>
    <body>
        <br/>
        <div class = "row">
            <div class = "col s6">
                <div class = "card orange darken-4">
                    <span class = "card-title white-text" style = "padding:5px;">My Info</span>
                    <div class = "card-content black-text white">
                        <p>
                            <ul>
                                <li><b>Name:</b> <%= @tenant.name%></li>
                                <li><b>Email:</b> <%= @tenant.email%></li>
                                <li><b>Phone Number:</b> <%= @tenant.phone_number%></li>
                                <%if @property %>
                                    <li><b>My Property:</b> <a class "waves-effect waves-teal btn-flat" href="<%= properties_path %>/<%= @property.id %>"><%= @property.name %> </a> </td>
                                    <li><b>Monthly Rent:</b> <%= @tenant.rentNum %></td>
                                <% else %>
                                    <li><b>My Property:</b> None</li>
                                <% end %>
                            </ul>
                        </p>
                    </div>
                    <div class = "card-action">
                        <a href = "/tenants/edit" class = "white-text">Edit</a>
                    </div>
                </div>
            </div>
        <% if not @roommates.nil? %>
            <% if not @roommates.empty? %>
                <div class = "col s6">
                    <div class = "card orange darken-4">
                        <span class = "card-title white-text" style = "padding:5px;">My Housemates</span>
                        <div class = "card-content black-text white">
                            <table class = "highlight"  >
                                <thead>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Phone Number</th>
                                    <th>Monthly Rent</th>
                                </thead>
                                <tbody>
                                    <% @roommates.each do |t| %>
                                        <tr>
                                            <td><%= t.name %></td>
                                            <td><%= t.email %></td>
                                            <td><%= t.phone_number %></td>
                                            <td><%= t.rentNum %></td>
                                        </tr>
                                    <% end %>
                                 </tbody>
                            </table>
                            <% if @roommateRentTot < @property.monthly_rent %> 
                                <span class = "red-text"><i class="material-icons left">warning</i> Your monthly rent is <%= @property.monthly_rent %>, but you have agreed to pay <%=@roommateRentTot%> in total.
                                <br/>Please adjust your monthly rent contributions.
                                </span>
                            <% end %>
                        </div>
                    </div>
                </div>
            <% end %>
        <% end %>
        <% if not @services.nil? %>
            <% if not @services.empty? %>
                <div class = "col s6">
                    <div class = "card orange darken-4">
                        <span class = "card-title white-text" style = "padding:5px;">Service Requests</span>
                        <div class = "card-content black-text white">
                            <table class = "highlight"  >
                                <thead>
                                    <th>Address</th>
                                    <th>Subject</th>
                                </thead>
                                <tbody>
                                    <% @services.each do |t| %>
                                        <tr>
                                            <td>  <a class "waves-effect waves-teal btn-flat" href="<%= services_path %>/<%= t.id %>"><%= t.address %> </a> </td>
                                            <td><%= t.subject %> </td>
                                        </tr>
                                    <% end %>
                                 </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            <% end %>
        <% end %>
        </div>
        <div class = "row">
            <div class = "col s6">
                <div class = "card orange darken-4">
                    <span class = "card-title white-text" style = "padding:5px;"> Rent</span>
                    <div class = "card-content black-text white">
                        <table class = "highlight"  >
                        <thead>
                            <th>Address</th>
                            <th>Amount Due</th>
                            <th>Total Due</th>
                            <th>Due By</th>
                            <th>Pay</th>
                            <th></th>
                        </thead>
                        <tbody>
                            <%if @property %>
                                    <% @tenant.rent.each do |r| %>
                                       <tr>
                                            <td><%= @property.address %> </a> </td>
                                            <% if @tenant.stripe_user_id.blank? %>
                                                <td><a href="https://connect.stripe.com/express/oauth/authorize?response_type=code&amp;client_id=ca_BxQ5lRqHMj8wNB7ypsxH0sl1XNkFJ9xE&amp;scope=read_write&amp;redirect_uri=https://property-site-2.herokuapp.com/tenants/show" class="stripe-connect"><span>Connect with Stripe</span></a></td>
                                            <% else %>
                                                <% if @tenant.rentNum.nil? %>
                                                    <td><a href = "/tenants/edit">Edit</a></td>
                                                <% else %>
                                                    <td><%= @tenant.rentNum %> </td>
                                                <% end %>
                                                <td><%= r.total %> </td>
                                                <td><%= r.due.month %>/<%= r.due.day %>/<%= r.due.year %></td>
                                                <!--<td>
                                                    <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
                                                        <input type="hidden" name="cmd" value="_xclick">
                                                        <input type="hidden" name="business" value="WC3NQBG6Q7WDS">
                                                        <input type="hidden" name="lc" value="US">
                                                        <input type="hidden" name="item_name" value="<%=@property.name%> Rent, <%= r.due.month %>/<%= r.due.year %> ">
                                                        <input type="hidden" name="button_subtype" value="services">
                                                        <input type="hidden" name="no_note" value="1">
                                                        <input type="hidden" name="no_shipping" value="1">
                                                        <input type="hidden" name="currency_code" value="USD">
                                                        <input type="hidden" name="bn" value="PP-BuyNowBF:btn_buynowCC_LG.gif:NonHosted">
                                                        <input type="hidden" name="amount" value="<%=@tenant.rentNum %>">
                                                        <input type="hidden" name="return" value-"https://property-site-2.herokuapp.com/tenants/pay/<%=r.id%>">
                                                        <input type="hidden" name="cancel_return" value-"https://property-site-2.herokuapp.com/tenants/show">
                                                        <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_paynow_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
                                                        <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
                                                    </form>
                                                </td>-->
                                                <td><a class "waves-effect waves-teal btn-flat" href="/tenants/pay/<%= r.id %>">Pay Rent</a></td>
                                            <% end %>
                                        </tr>
                                    <% end %>
                                </tr>
                            <% end %>
                        </tbody>
                    </table>
                    </div>
                </div>
            </div>
        </div>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    </body>
</html>