config/routes.rb
Rails.application.routes.draw do
  resources :properties
  root :to => redirect('/home')
  
  get '/home' => 'sessions#home'
  post '/search' => 'sessions#search'
  get '/join/:id/:pid' => 'sessions#sendreq'
  get '/create' => 'sessions#create'
  get '/signin' => 'sessions#signin'
  post '/signin/:op' => 'sessions#new'
  post '/create/manager/:op' => 'sessions#createManager'
  post '/create/tenant/:op' => 'sessions#createTenant'
  get  'auth/:provider/callback' => 'sessions#facebookcheck'
  get '/create/manager' => 'sessions#createManager'
  get '/create/tenant' => 'sessions#createTenant'
  get 'logout' => 'sessions#destroy'
  get  'auth/failure' => 'sessions#failure'
  get  'auth/facebook', :as => 'login'
  get '/create/manager/check' => 'sessions#Managerfb'
  get '/create/tenant/check' => 'sessions#Tenantfb'
  get '/create/check' => 'sessions#signinfb'
  
  get '/request/:op/:id' => 'managers#respond'
  get '/managers/show' => 'managers#show'
  get '/managers/edit' => 'managers#edit'
  patch '/managers/edit' => 'managers#update'
  
  get '/tenants/show' => 'tenants#show'
  get '/tenants' => 'tenants#index'
  get '/tenants/new' => 'tenants#new'
  post '/tenants/new' => 'tenants#create'
  get '/tenants/edit' => 'tenants#edit'
  patch '/tenants/edit' => 'tenants#update'
  get '/tenants/pay' => 'tenants#pay'
  get '/tenants/pay/:id' => 'tenants#stripepay'
  get '/tenants/:op/:id' => 'tenants#service'

  get '/properties' => 'properties#index'
  get '/properties/:id' => 'properties#show'
  get '/properties/new' => 'properties#new'
  post '/properties/new' => 'properties#create'
  get '/properties/:id/edit' => 'properties#edit'
  delete '/properties/:id/delete' => 'properties#destroy'
  
  get '/services/new' => 'services#new'
  post '/services/new' => 'services#create'
  get '/services' => 'services#index'
  get '/services/:id' => 'services#show'
  
    get 'auth/guest', to: 'sessions#create_guest'
    get 'auth/loggedin', to: 'sessions#loggedin'
  

end

app/models/property.rb
class Property < ActiveRecord::Base
    #every property belongs to a manager
    belongs_to :manager
    #multiple people live in properties
    has_many :tenants
    has_many :joinrequests
    has_many :services
    has_many :rents
    #creates validation requirements 
    validates :name, :presence => true
    validates :address, :presence => true
    validates :square_feet, :presence => true
    validates :max_num_tenants, :presence => true
    validates :curr_num_tenants, :presence => true
    validates :monthly_rent, :presence => true
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  #before_action :force_log_in
  skip_before_action :verify_authenticity_token
  before_action :confirm_logged_in
  
  #shows all propertyies that have the manager id of the current manager 
  def index
    @manager = Manager.find(session[:user_id])
    @properties = Property.where(:manager_id => @manager)
  end
  #gives more infromation about a singular property. Must be on the manager owns
  def show
    @property = Property.find(params[:id])
    @tenants = Tenant.where(:property_id => @property.id)
  end
 #creates new property  
  def new
    @property = Property.new
  end
  #maps the features to the new property 
  def create
    params_map = ActiveSupport::HashWithIndifferentAccess.new(params[:property])
    @property = Property.new(params_map)
    #creates property with the current managers id for manager id 
    @property.manager_id = session[:user_id]
    if @property.save
            flash[:notice] = "#{@property.name} was successfully created."
        else
            flash[:notice] = "Property could not be created because #{@property.errors.full_messages}"
        end
    redirect_to properties_path
  end
 #allows for the editting of a property by the manager only 
  def edit
    @property = Property.find(params[:id])
  end
 #updates the features of the property to the new information 
  def update
    @property = Property.find(params[:id])
    params_map = ActiveSupport::HashWithIndifferentAccess.new(params[:property])
    @property.update(params_map)
    redirect_to @property
  end
  
  #deletes a property
  def destroy
  @property = Property.find(params[:id])
  @property.destroy
  flash[:notice] = "Property '#{@property.name}' at '#{@property.address}' deleted."
  redirect_to properties_path
end
  
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/edit.html.erb
<!DOCTYPE html>
<html>
    <head>
        <% @title="Edit Property Page: Abode" %>
    </head>
    <%= render '/layouts/manager_nav_bar' %>
    <% if flash[:notice] %>
        <div class="card-panel teal lighten-2 col s3 white-text">
            <%= flash[:notice] %>
        </div>
    <% end %>
    <body>
        <div class = "container">
            <div class = "row">
                <h3>
                   Edit Property
                </h3>
            </div>
            <!jfjfj>
            <div class = "row">
                <%= form_for @property do |f| %>
                    <div class = "row">
                        <div class = "col s6">
                            <label for="property_name">Property Name</label>
                            <%=  f.text_field :name, :class => "input-field "%>
                        </div>
                        <div class = "col s6">
                            <label for="property_address">Address</label>
                            <%=  f.text_field :address, :class => "input-field" %>
                        </div>
                    </div>
                    <div class = "row">
                        <div class = "col s3"
                            <label for="property_square_feet">Square Feet</label>
                            <%=  f.number_field :square_feet, :class => "input-field" %>
                        </div>
                        <div class = "col s3">
                            <label for="property_max_num_tenants">Capacity</label>
                            <%=  f.number_field :max_num_tenants, :class => "input-field" %>
                        </div>
                        <div class = "col s3">
                            <label for="property_curr_num_tenants">Current Occupants</label>
                            <%=  f.number_field :curr_num_tenants, :class => "input-field " %>
                        </div>
                        <div class = "col s3">
                            <label for="property_monthly_rent">Monthly Rent</label>
                            <%=  f.number_field :monthly_rent, :class => "input-field" %>
                        </div>
                    </div>
                    <div class = "row">
                        <div class = "input-field col s8">
                            <label for="property_notes">Notes</label>
                            <%= f.text_area :notes, :class => "materialize-textarea"  %>
                        </div>
                    </div>
                    <br/><br/>
                    <div class = "row">
                        <%= f.submit "Update", class: "btn btn-primary" %>
                    </div>
                <% end %>
            </div>
        </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    </body>
</html>

app/views/properties/index.html.erb
<!DOCTYPE html>
<html>
    <head>
        <% @title="Property Page: Abode" %>
    </head>
     <%= render '/layouts/manager_nav_bar' %>
     <% if flash[:notice] %>
        <div class="card-panel teal lighten-2 col s3 white-text">
            <%= flash[:notice] %>
        </div>
    <% end %>
    <body>
        <div class = "container">
            <div class = "row">
                <h1>Properties</h1>
            </div>
            <div class = "row" id = "proptable">
                <table class = "highlight"  >
                    <thead>
                        <th></th>
                        <th>Address</th>
                        <th>Square Ft.</th>
                        <th>Capacity</th>
                        <th>Current Tenants</th>
                        <th>Monthly Rent</th>
                        <th>Notes</th>
                    </thead>
                    <tbody>
                        <%if @properties
                        @properties.each do |t| %>
                            <tr>
                                <td>  <a class "waves-effect waves-teal btn-flat" href="<%= properties_path %>/<%= t.id %>"><%= t.name %> </a> </td>
                                <td><%= t.address %></td>
                                <td><%= t.square_feet%> </td>
                                <td><%= t.max_num_tenants%>   </td>
                                <td><%= t.curr_num_tenants%>   </td>
                                <td><%= t.monthly_rent%>   </td>
                                <td><%= t.notes%>   </td>
                                <td>  <a class "waves-effect waves-teal btn-flat" href="<%= properties_path %>/<%= t.id %>/edit" id = "Edit">Edit</a> </td>
                            </tr>
                        <%end 
                         end%>
                     </tbody>
                </table>
            </div>
            <br/>
            <div class = "row">
                <div>
                    <a class = "waves-effect waves-light btn" href = "<%=properties_path%>/new" id = "create">Create New</a>
                </div>
            </div>
        </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    </body>
</html>

app/views/properties/new.html.erb
<!DOCTYPE html>
<html>
    <head>
        <% @title="Create Property Page: Abode" %>
    </head>
    <%= render '/layouts/manager_nav_bar' %>
    <% if flash[:notice] %>
        <div class="card-panel teal lighten-2 col s3 white-text">
            <%= flash[:notice] %>
        </div>
    <% end %>
    <body>
        <div class = "container">
            <div class = "row">
                <h3>
                    Create New Property
                </h3>
            </div>
            <div class = "row">
                <form class = "col s12" action = "<%properties_path%>" method = "post">
                    <div class = "row">
                        <div class = "input-field col s6">
                            <input id="property_name" name = "property[name]" type="text" class="validate" maxlength="25" required="true">
                            <label for="property_name">Property Name</label>
                        </div>
                        <div class = "input-field col s6">
                            <input id="property_address" name = "property[address]" type="text" class="validate" maxlength="25" required="true">
                            <label for="property_address">Address</label>
                        </div>
                    </div>
                    <div class = "row">
                        <div class = "input-field col s3">
                            <input id="property_square_feet" name = "property[square_feet]" type="text"  class="validate" maxlength="7" required="true">
                            <label for="property_square_feet">Square Feet</label>
                        </div>
                        <div class = "input-field col s3">
                            <input id="property_max_num_tenants" name = "property[max_num_tenants]" type="number" class="validate" maxlength="2" required="true">
                            <label for="property_max_num_tenants">Capacity</label>
                        </div>
                        <div class = "input-field col s3">
                            <input id="property_curr_num_tenants" name = "property[curr_num_tenants]" type="number" class="validate" maxlength="2" required="true">
                            <label for="property_curr_num_tenants">Current Occupants</label>
                        </div>
                        <div class = "col s3">
                            $
                            <div class ="input-field inline">
                                <input id="property_monthly_rent" name = "property[monthly_rent]" type = "number" class= "validate" maxlength="5" required="true">
                                <label for="property_monthly_rent">Monthly Rent</label>
                            </div>
                        </div>
                    </div>
                    <div class = "row">
                        <div class = "input-field col s8">
                            <textarea class = "materialize-textarea" id="property_notes" name = "property[notes]" maxlength="140"></textarea>
                            <label for="property_notes">Notes</label>
                        </div>
                    </div>
                    <div class = "input-field col s3">
                        <input name="commit" type="submit" value="Create" id="create" class = "waves-effect waves-light btn"/>
                    </div>
                </form>
            </div>
        </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    </body>
</html>

app/views/properties/show.html.erb
<!DOCTYPE html>
<html>
    <head>
        <% @title="Property Info Page: Abode" %>
    </head>
    <% if session[:check] == 1 %>
        <%= render '/layouts/manager_nav_bar' %>
    <% else %>
        <%= render '/layouts/tenant_nav_bar' %>
    <% end %>
    <% if flash[:notice] %>
        <div class="card-panel teal lighten-2 col s3 white-text">
            <%= flash[:notice] %>
        </div>
    <% end %>
    <body>
        <!-- shows all the atributes -->
        <div class= "container">
            <div class = "row">
                <h1>Properties</h1>
            </div>
        </div>
        <div class = "row">
            <table class = "highlight">
                
                <thead>
                    <th></th>
                    <th>Address</th>
                    <th>Square Ft.</th>
                    <th>Capacity</th>
                    <th>Current Tenants</th>
                    <th>Monthly Rent</th>
                    <th>Notes</th>
                </thead>
                <tbody>
                    <%if @property %>
                        <tr>
                            <td><%= @property.name %> </a> </td>
                            <td><%= @property.address %> </a> </td>
                            <td><%= @property.square_feet %> </a> </td>
                            <td><%= @property.max_num_tenants%> </td>
                            <td><%= @property.curr_num_tenants%> </td>
                            <td><%= @property.monthly_rent %> </td>
                            <td><%= @property.notes %> </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
        <br/>
        <% if session[:check] == 1 %>
            <div class = "row">
                <%= link_to "Delete", property_path(@property), :method => :delete %>
            </div>
        <% end %>
        <div class = "row">
            <table class = "highlight">
                <thead>
                    <th>Name</th>
                    <th>Phone Number</th>
                    <th>Email</th>
                </thead>
                <tbody>
                    <%if @tenants 
                    @tenants.each do |t| %>
                        <tr>
                            <td><%= t.name%> </td>
                            <td><%= t.phone_number%> </td>
                            <td><%= t.email%> </td>
                        </tr>
                    <% end 
                    end %>
                </tbody>
            </table>
        </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    </body>
    
</html>