config/routes.rb
Rails.application.routes.draw do
  resources :properties
  root :to => redirect('/home')
  
  get '/home' => 'sessions#home'
  post '/search' => 'sessions#search'
  get '/join/:id/:pid' => 'sessions#sendreq'
  get '/create' => 'sessions#create'
  get '/signin' => 'sessions#signin'
  post '/signin/:op' => 'sessions#new'
  post '/create/manager/:op' => 'sessions#createManager'
  post '/create/tenant/:op' => 'sessions#createTenant'
  get  'auth/:provider/callback' => 'sessions#facebookcheck'
  get '/create/manager' => 'sessions#createManager'
  get '/create/tenant' => 'sessions#createTenant'
  get 'logout' => 'sessions#destroy'
  get  'auth/failure' => 'sessions#failure'
  get  'auth/facebook', :as => 'login'
  get '/create/manager/check' => 'sessions#Managerfb'
  get '/create/tenant/check' => 'sessions#Tenantfb'
  get '/create/check' => 'sessions#signinfb'
  
  get '/request/:op/:id' => 'managers#respond'
  get '/managers/show' => 'managers#show'
  get '/managers/edit' => 'managers#edit'
  patch '/managers/edit' => 'managers#update'
  
  get '/tenants/show' => 'tenants#show'
  get '/tenants' => 'tenants#index'
  get '/tenants/new' => 'tenants#new'
  post '/tenants/new' => 'tenants#create'
  get '/tenants/edit' => 'tenants#edit'
  patch '/tenants/edit' => 'tenants#update'
  get '/tenants/pay' => 'tenants#pay'
  get '/tenants/pay/:id' => 'tenants#stripepay'
  get '/tenants/:op/:id' => 'tenants#service'

  get '/properties' => 'properties#index'
  get '/properties/:id' => 'properties#show'
  get '/properties/new' => 'properties#new'
  post '/properties/new' => 'properties#create'
  get '/properties/:id/edit' => 'properties#edit'
  delete '/properties/:id/delete' => 'properties#destroy'
  
  get '/services/new' => 'services#new'
  post '/services/new' => 'services#create'
  get '/services' => 'services#index'
  get '/services/:id' => 'services#show'
  
    get 'auth/guest', to: 'sessions#create_guest'
    get 'auth/loggedin', to: 'sessions#loggedin'
  

end

app/views/layouts/_manager_nav_bar.html.erb
<!--creates the navigation bar for all managers!-->

    <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    </head>
    <body>
        <nav>
            <div class="nav-wrapper orange darken-4">
                <a href="/home" class="brand-logo" style = "margin-left:10px;" >Abode</a>
                <ul id="nav-mobile" class="right hide-on-med-and-down">
                    <!--managers have the buttons: properties, profile, and log out!-->
                    <li><a href="/managers/show"><i class="material-icons left">person_pin</i>My Profile</a></li>
                    <li><a href= "<%=properties_path %>"><i class="material-icons left">home</i>My Properties</a></li>
                    <li><a href="/logout"><i class="material-icons left">power_settings_new</i>Log Out</a></li>
                </ul>
            </div>
        </nav>
    </div>
  </div>
    </body>

app/views/layouts/_nav_bar.html.erb
    <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    </head>
    <body>
        <nav>
            <div class="nav-wrapper orange darken-4">
                <a href="<%= properties_path %>" class="brand-logo">Home</a>
                <ul id="nav-mobile" class="right hide-on-med-and-down">
                    <li><a href="/logout">Log Out</a></li>
                    <li><a href="#">Buttons!</a></li>
                    <li><a href="#">Buttons!</a></li>
                </ul>
            </div>
        </nav>
    </div>
  </div>
    </body>

app/views/layouts/_tenant_nav_bar.html.erb
    <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    </head>
    <body>
        <nav>
            <div class="nav-wrapper teal lighten-2">
                <a href= "<%= tenants_path %>/show" class="brand-logo" style = "margin-left:10px;">Abode</a>
                <ul id="nav-mobile" class="right hide-on-med-and-down">
                    <!--makes sure tenant is in a property to make service requests!-->
                    <li><a href="<%= tenants_path %>/show"><i class="material-icons left">person_pin</i>My Profile</a></li>
                    <% if not @tenant.property_id.blank? %> 
                    <li><a href="<%= services_new_path %>"><i class="material-icons left">build</i>Service Request</a></li>
                    <% else %> 
                    <!-- if not in a property, the tenant has the ability to search for properties !-->
                    <li><a href="/search"><i class="material-icons left">search</i>Search</a></li>
                    <% end %>
                    <li><a href="/logout"><i class="material-icons left">power_settings_new</i>Log Out</a></li>
                </ul>
            </div>
        </nav>
    </div>
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<!--<%= debug(params) if Rails.env.development? %>-->
</body>
</html>